//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektPrototyp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokoj
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pokoj()
        {
            this.Student = new HashSet<Student>();
        }
    
        public int id_pokoju { get; set; }
        public int nr_pokoju { get; set; }
        public bool czy_lazienka { get; set; }
        public int id_budynku { get; set; }
    
        public virtual Budynek Budynek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Student { get; set; }
    }
}
