//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektPrototyp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int id_studenta { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string pesel { get; set; }
        public string telefon { get; set; }
        public int id_adresu { get; set; }
        public int id_kierunku { get; set; }
        public int id_pokoju { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual Kierunek Kierunek { get; set; }
        public virtual Pokoj Pokoj { get; set; }
    }
}
